// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelInstall(): $CancellablePromise<void> {
    return $Call.ByID(2625956878);
}

export function CheckForUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4076042935);
}

export function CreateGameWindow(): $CancellablePromise<void> {
    return $Call.ByID(515728507);
}

export function GetGameState(): $CancellablePromise<$models.GameState> {
    return $Call.ByID(1448081722).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartInstall(): $CancellablePromise<void> {
    return $Call.ByID(3525102106);
}

export function StartUpdate(): $CancellablePromise<void> {
    return $Call.ByID(519653914);
}

// Private type creation functions
const $$createType0 = $models.GameState.createFrom;
