// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelInstall(): $CancellablePromise<void> {
    return $Call.ByID(2625956878);
}

export function CheckForUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4076042935);
}

export function GetGameState(): $CancellablePromise<$models.GameState> {
    return $Call.ByID(1448081722).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetLauncherInfo(): $CancellablePromise<$models.LauncherInfo> {
    return $Call.ByID(2292426071).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LaunchGame(): $CancellablePromise<void> {
    return $Call.ByID(2893946080);
}

export function OpenGameFolder(): $CancellablePromise<void> {
    return $Call.ByID(1309839059);
}

export function OpenGameRepository(): $CancellablePromise<void> {
    return $Call.ByID(2976509643);
}

export function OpenLauncherRepository(): $CancellablePromise<void> {
    return $Call.ByID(2042697873);
}

export function StartInstall(): $CancellablePromise<void> {
    return $Call.ByID(3525102106);
}

export function StartUpdate(): $CancellablePromise<void> {
    return $Call.ByID(519653914);
}

// Private type creation functions
const $$createType0 = $models.GameState.createFrom;
const $$createType1 = $models.LauncherInfo.createFrom;
