// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CloseGuardEvent tells the frontend why a close request was intercepted.
 */
export class CloseGuardEvent {
    "mode": CloseGuardMode;
    "progressPhase": string;

    /** Creates a new CloseGuardEvent instance. */
    constructor($$source: Partial<CloseGuardEvent> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = CloseGuardMode.$zero;
        }
        if (!("progressPhase" in $$source)) {
            this["progressPhase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseGuardEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseGuardEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseGuardEvent($$parsedSource as Partial<CloseGuardEvent>);
    }
}

export enum CloseGuardMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    closeGuardConfirmCancel = "confirm_cancel",
    closeGuardBlocked = "blocked",
};

/**
 * GameBrowser is a browser that the operating system has registered as able to
 * open the game's local HTML entry point. ID is an opaque platform identifier;
 * callers must not interpret it as an executable path or command.
 */
export class GameBrowser {
    "id": string;
    "name": string;

    /** Creates a new GameBrowser instance. */
    constructor($$source: Partial<GameBrowser> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameBrowser instance from a string or object.
     */
    static createFrom($$source: any = {}): GameBrowser {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameBrowser($$parsedSource as Partial<GameBrowser>);
    }
}

export class GameFolderChangeResult {
    "cancelled": boolean;
    "applied": boolean;
    "requiresMove": boolean;
    "root": string;
    "gamePath": string;
    "currentGamePath": string;

    /** Creates a new GameFolderChangeResult instance. */
    constructor($$source: Partial<GameFolderChangeResult> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }
        if (!("applied" in $$source)) {
            this["applied"] = false;
        }
        if (!("requiresMove" in $$source)) {
            this["requiresMove"] = false;
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("gamePath" in $$source)) {
            this["gamePath"] = "";
        }
        if (!("currentGamePath" in $$source)) {
            this["currentGamePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameFolderChangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameFolderChangeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameFolderChangeResult($$parsedSource as Partial<GameFolderChangeResult>);
    }
}

export class GameFolderInfo {
    "root": string;
    "gamePath": string;
    "defaultRoot": string;
    "isDefault": boolean;

    /** Creates a new GameFolderInfo instance. */
    constructor($$source: Partial<GameFolderInfo> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("gamePath" in $$source)) {
            this["gamePath"] = "";
        }
        if (!("defaultRoot" in $$source)) {
            this["defaultRoot"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameFolderInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GameFolderInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameFolderInfo($$parsedSource as Partial<GameFolderInfo>);
    }
}

/**
 * GameLaunchResult describes a successful launch. FallbackToDefault is true
 * only when the selected browser failed and the system default handler then
 * accepted the game entry.
 */
export class GameLaunchResult {
    "fallbackToDefault": boolean;

    /** Creates a new GameLaunchResult instance. */
    constructor($$source: Partial<GameLaunchResult> = {}) {
        if (!("fallbackToDefault" in $$source)) {
            this["fallbackToDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLaunchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLaunchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameLaunchResult($$parsedSource as Partial<GameLaunchResult>);
    }
}

export class GameState {
    "revision": number;
    "status": GameStatus;
    "commit": string;
    "commitTime": string;
    "remoteCommit": string;
    "remoteCommitTime": string;
    "updateAvailable": boolean;
    "progressPhase": string;
    "progressText": string;
    "progressPercent": number;
    "progressSeconds": number;
    "progressStep": number;
    "progressStepTotal": number;
    "progressCancellable": boolean;
    "message": string;
    "error": string;

    /** Creates a new GameState instance. */
    constructor($$source: Partial<GameState> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = GameStatus.$zero;
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("commitTime" in $$source)) {
            this["commitTime"] = "";
        }
        if (!("remoteCommit" in $$source)) {
            this["remoteCommit"] = "";
        }
        if (!("remoteCommitTime" in $$source)) {
            this["remoteCommitTime"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            this["updateAvailable"] = false;
        }
        if (!("progressPhase" in $$source)) {
            this["progressPhase"] = "";
        }
        if (!("progressText" in $$source)) {
            this["progressText"] = "";
        }
        if (!("progressPercent" in $$source)) {
            this["progressPercent"] = 0;
        }
        if (!("progressSeconds" in $$source)) {
            this["progressSeconds"] = 0;
        }
        if (!("progressStep" in $$source)) {
            this["progressStep"] = 0;
        }
        if (!("progressStepTotal" in $$source)) {
            this["progressStepTotal"] = 0;
        }
        if (!("progressCancellable" in $$source)) {
            this["progressCancellable"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameState instance from a string or object.
     */
    static createFrom($$source: any = {}): GameState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameState($$parsedSource as Partial<GameState>);
    }
}

export enum GameStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusMissing = "missing",
    StatusResolving = "resolving",
    StatusInstalling = "installing",
    StatusReady = "ready",
    StatusChecking = "checking",
    StatusUpdateAvailable = "update_available",
    StatusUpdating = "updating",
    StatusRecovering = "recovering",
    StatusRecoveryFailed = "recovery_failed",
    StatusMoving = "moving",
    StatusStorageUnavailable = "storage_unavailable",
    StatusCancelled = "cancelled",
    StatusError = "error",
};

export class LauncherInfo {
    "version": string;
    "gameRepository": string;

    /** Creates a new LauncherInfo instance. */
    constructor($$source: Partial<LauncherInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("gameRepository" in $$source)) {
            this["gameRepository"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LauncherInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LauncherInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LauncherInfo($$parsedSource as Partial<LauncherInfo>);
    }
}
