// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GameState {
    "revision": number;
    "status": GameStatus;
    "commit": string;
    "remoteCommit": string;
    "updateAvailable": boolean;
    "progressPhase": string;
    "progressText": string;
    "progressPercent": number;
    "progressSeconds": number;
    "message": string;
    "error": string;

    /** Creates a new GameState instance. */
    constructor($$source: Partial<GameState> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = GameStatus.$zero;
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("remoteCommit" in $$source)) {
            this["remoteCommit"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            this["updateAvailable"] = false;
        }
        if (!("progressPhase" in $$source)) {
            this["progressPhase"] = "";
        }
        if (!("progressText" in $$source)) {
            this["progressText"] = "";
        }
        if (!("progressPercent" in $$source)) {
            this["progressPercent"] = 0;
        }
        if (!("progressSeconds" in $$source)) {
            this["progressSeconds"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameState instance from a string or object.
     */
    static createFrom($$source: any = {}): GameState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameState($$parsedSource as Partial<GameState>);
    }
}

export enum GameStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusMissing = "missing",
    StatusResolving = "resolving",
    StatusInstalling = "installing",
    StatusReady = "ready",
    StatusChecking = "checking",
    StatusUpdateAvailable = "update_available",
    StatusUpdating = "updating",
    StatusCancelled = "cancelled",
    StatusError = "error",
};
