// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GameState {
    "status": GameStatus;
    "commit": string;
    "receivedBytes": number;
    "totalBytes": number;
    "filesExtracted": number;
    "message": string;
    "error": string;

    /** Creates a new GameState instance. */
    constructor($$source: Partial<GameState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = GameStatus.$zero;
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("receivedBytes" in $$source)) {
            this["receivedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("filesExtracted" in $$source)) {
            this["filesExtracted"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameState instance from a string or object.
     */
    static createFrom($$source: any = {}): GameState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameState($$parsedSource as Partial<GameState>);
    }
}

export enum GameStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusMissing = "missing",
    StatusResolving = "resolving",
    StatusInstalling = "installing",
    StatusReady = "ready",
    StatusCancelled = "cancelled",
    StatusError = "error",
};
